---
title: Sarah Beck Mather
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.sarahbeckmather.com
description: "Sarah lives and works in London as a self-supporting Artist. Whilst
  she trained as an actor at The Central School of Speech and Drama, she has maintained
  her artistic practice throughout, and her interaction and involvement with painting
  has continued to grow and deepen over time. She has continued to develop as an artist—specialising
  in abstract paintings, employing mixed media—and she makes personal and intuitive
  work that is available to buy; she is also prepared to undertake commissions. Her
  work is atmospheric and suffused with allusions to landscape; it is emotionally
  charged, and the experience of being a working actor has given it a force and presence.
  For her, the painted image continues to be an important focus for the world of feeling
  and perception, and is seen as an important aspect of being alive.\n\n"
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Sarah Beck Mather
email: info@sarahbeckmather.com
google_site_verification: odnYOu7QbasbH7jmia72yczLvoplsBQ034yf3IPqFks
analytics: UA-92845653-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/sarahbeckmatherart/
  instagram: https://www.instagram.com/sarah_beck_mather/
  twitter: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: sarah-beck-mather.imgix.net
